"dein.vim
if &compatible
  set nocompatible
endif

"set runtimepath+=~/.vimrt/plugins/repos/github.com/Shougo/dein.vim
set runtimepath+=~/.vimrt/vim

" Set up the plugin mngr
if empty(glob('~/.vimrt/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vimrt/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  'autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


source ~/.vimrt/vimrcs/plugged.vim
source ~/.vimrt/vimrcs/general.vim
source ~/.vimrt/vimrcs/plugins.vim
source ~/.vimrt/vimrcs/filetypes.vim

try
source ~/.vimrt/vimrcs/scratch.vim
catch
endtry
