#!/bin/sh

# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

[ -f ~/.config/i3/config.common ] && cat ~/.config/i3/config.common > ~/.config/i3/config
[ -f ~/.config/i3/config.local ] && cat ~/.config/i3/config.local >> ~/.config/i3/config

#exec i3 -V >> ~/i3log-$(date +'%F-%k-%M-$S') 2>&1
dbus-update-activation-environment --systemd DISPLAY

# Remap caps to escape
setxkbmap -option caps:escape

# Make repitition faster
xset r rate 300 50

xrdb-merge ~/.Xresources
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets)
export SSH_AUTH_SOCK
exec i3
#/usr/bin/X11/xterm &
